# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - dailypet

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Print current directory
        run: pwd

      - name: List contents of the project root
        run: ls -alh

      - name: List contents of target directory
        run: ls -alh target/

      - name: List contents of the ABSOLUTE target directory
        run: ls -alh ${{ github.workspace }}/target/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/dailypet-0.0.1-SNAPSHOT.jar'

      - name: Check artifact after upload
        run: ls -alh ${{ github.workspace }}/target/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write 
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: List contents of the downloaded artifact directory
        run: ls -alh ${{ github.workspace }}

      - name: Verify downloaded files
        run: ls -alh

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dailypet'  # Your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Publish profile from Azure portal
          package: '${{ github.workspace }}/dailypet-0.0.1-SNAPSHOT.jar'
